import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'bg-base': 'var(--bg-base)',
        'bg-surface': 'var(--bg-surface)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-overlay': 'var(--bg-overlay)',
        accent: 'var(--accent)',
        'accent-dim': 'var(--accent-dim)',
        'accent-glow': 'var(--accent-glow)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        border: 'var(--border)',
        'border-accent': 'var(--border-accent)',
        divider: 'var(--divider)',
        scrim: 'var(--scrim)',
        danger: 'var(--danger)',
        warning: 'var(--warning)',
        success: 'var(--success)',
        info: 'var(--info)',
        'button-primary': 'var(--button-primary-bg)',
        'button-primary-hover': 'var(--button-primary-bg-hover)',
        'button-primary-active': 'var(--button-primary-bg-active)',
        'button-primary-foreground': 'var(--button-primary-fg)',
        'button-secondary': 'var(--button-secondary-bg)',
        'button-secondary-hover': 'var(--button-secondary-bg-hover)',
        'button-secondary-active': 'var(--button-secondary-bg-active)',
        'button-secondary-border': 'var(--button-secondary-border)',
        'button-secondary-foreground': 'var(--button-secondary-fg)',
        'button-outline': 'var(--button-outline-bg)',
        'button-outline-hover': 'var(--button-outline-bg-hover)',
        'button-outline-active': 'var(--button-outline-bg-active)',
        'button-outline-border': 'var(--button-outline-border)',
        'button-outline-foreground': 'var(--button-outline-fg)',
        'button-ghost': 'var(--button-ghost-bg)',
        'button-ghost-hover': 'var(--button-ghost-bg-hover)',
        'button-ghost-active': 'var(--button-ghost-bg-active)',
        'button-ghost-foreground': 'var(--button-ghost-fg)',
        'button-ghost-foreground-hover': 'var(--button-ghost-fg-hover)',
        'button-danger': 'var(--button-danger-bg)',
        'button-danger-hover': 'var(--button-danger-bg-hover)',
        'button-danger-active': 'var(--button-danger-bg-active)',
        'button-danger-border': 'var(--button-danger-border)',
        'button-danger-foreground': 'var(--button-danger-fg)',
        'button-focus-ring': 'var(--button-focus-ring)',
        'button-focus-offset': 'var(--button-focus-offset)',
        input: 'var(--input-bg)',
        'input-filled': 'var(--input-filled-bg)',
        'input-outlined': 'var(--input-outlined-bg)',
        'input-border': 'var(--input-border)',
        'input-border-hover': 'var(--input-border-hover)',
        'input-border-focus': 'var(--input-border-focus)',
        'input-border-error': 'var(--input-border-error)',
        'input-border-success': 'var(--input-border-success)',
        'input-text': 'var(--input-text)',
        'input-label': 'var(--input-label)',
        'input-placeholder': 'var(--input-placeholder)',
        'input-icon': 'var(--input-icon)',
        'input-icon-hover': 'var(--input-icon-hover)',
        select: 'var(--select-bg)',
        'select-filled': 'var(--select-filled-bg)',
        'select-outlined': 'var(--select-outlined-bg)',
        'select-border': 'var(--select-border)',
        'select-border-hover': 'var(--select-border-hover)',
        'select-border-focus': 'var(--select-border-focus)',
        'select-border-error': 'var(--select-border-error)',
        'select-border-success': 'var(--select-border-success)',
        'select-text': 'var(--select-text)',
        'select-label': 'var(--select-label)',
        'select-placeholder': 'var(--select-placeholder)',
        'select-icon': 'var(--select-icon)',
      },
      fontFamily: {
        sans: ['var(--font-family-sans)'],
      },
      fontSize: {
        xs: ['var(--font-size-xs)', { lineHeight: 'var(--line-height-xs)' }],
        sm: ['var(--font-size-sm)', { lineHeight: 'var(--line-height-sm)' }],
        base: ['var(--font-size-base)', { lineHeight: 'var(--line-height-base)' }],
        lg: ['var(--font-size-lg)', { lineHeight: 'var(--line-height-lg)' }],
        xl: ['var(--font-size-xl)', { lineHeight: 'var(--line-height-xl)' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-2xl)' }],
        '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-3xl)' }],
      },
      fontWeight: {
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
        black: 'var(--font-weight-black)',
      },
      letterSpacing: {
        tight: 'var(--letter-spacing-tight)',
        normal: 'var(--letter-spacing-normal)',
        wide: 'var(--letter-spacing-wide)',
        widest: 'var(--letter-spacing-widest)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
        chip: 'var(--radius-chip)',
        control: 'var(--radius-control)',
        card: 'var(--radius-card)',
        panel: 'var(--radius-panel)',
        pill: 'var(--radius-pill)',
      },
      maxWidth: {
        app: 'var(--layout-app-max-width)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        modal: 'var(--shadow-modal)',
        'glow-accent': 'var(--glow-accent)',
        'glow-accent-sm': 'var(--glow-accent-sm)',
        'button-focus': 'var(--button-focus-shadow)',
        'input-focus': 'var(--input-focus-shadow)',
        'select-focus': 'var(--select-focus-shadow)',
      },
      spacing: {
        micro: 'var(--spacing-micro)',
        xs: 'var(--spacing-xs)',
        sm: 'var(--spacing-sm)',
        md: 'var(--spacing-md)',
        lg: 'var(--spacing-lg)',
        page: 'var(--spacing-page)',
        section: 'var(--spacing-section)',
        'section-top': 'var(--spacing-xl)',
        'header-height': 'var(--layout-header-height)',
        'bottom-nav-height': 'var(--layout-bottom-nav-height)',
        'touch-target': 'var(--layout-touch-target-min)',
        'primary-action': 'var(--layout-primary-action-height)',
        'button-sm': 'var(--button-height-sm)',
        'button-md': 'var(--button-height-md)',
        'button-lg': 'var(--button-height-lg)',
        'button-padding-sm': 'var(--button-padding-sm)',
        'button-padding-md': 'var(--button-padding-md)',
        'button-padding-lg': 'var(--button-padding-lg)',
        'button-gap-sm': 'var(--button-gap-sm)',
        'button-gap-md': 'var(--button-gap-md)',
        'button-gap-lg': 'var(--button-gap-lg)',
        'button-icon-sm': 'var(--button-icon-sm)',
        'button-icon-md': 'var(--button-icon-md)',
        'button-icon-lg': 'var(--button-icon-lg)',
        input: 'var(--input-height)',
        'input-padding': 'var(--input-padding-x)',
        'input-label-offset': 'var(--input-label-offset)',
        'input-message-gap': 'var(--input-message-gap)',
        'input-action': 'var(--input-action-area)',
        'input-actions': 'var(--input-actions-area)',
        'input-icon': 'var(--input-icon-size)',
        select: 'var(--select-height)',
        'select-padding': 'var(--select-padding-x)',
        'select-label-offset': 'var(--select-label-offset)',
        'select-message-gap': 'var(--select-message-gap)',
        'select-action': 'var(--select-action-area)',
        'select-icon': 'var(--select-icon-size)',
        'safe-bottom': 'var(--safe-area-bottom)',
        'safe-top': 'var(--safe-area-top)',
      },
      zIndex: {
        base: 'var(--z-base)',
        content: 'var(--z-content)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        navigation: 'var(--z-navigation)',
        overlay: 'var(--z-overlay)',
      },
      transitionDuration: {
        micro: 'var(--duration-micro)',
        fast: 'var(--duration-fast)',
        state: 'var(--duration-state)',
        overlay: 'var(--duration-overlay)',
        entry: 'var(--duration-entry)',
        maximum: 'var(--duration-maximum)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        progress: 'var(--ease-progress)',
        linear: 'var(--ease-linear)',
      },
      transitionProperty: {
        button: 'var(--button-transition-properties)',
        input: 'var(--input-transition-properties)',
        select: 'var(--select-transition-properties)',
      },
      scale: {
        'button-pressed': 'var(--button-pressed-scale)',
      },
      animation: {
        'button-spinner': 'spin var(--button-spinner-duration) var(--ease-linear) infinite',
        'input-spinner': 'spin var(--input-spinner-duration) var(--ease-linear) infinite',
        'select-spinner': 'spin var(--select-spinner-duration) var(--ease-linear) infinite',
      },
      opacity: {
        hidden: 'var(--opacity-hidden)',
        subtle: 'var(--opacity-subtle)',
        soft: 'var(--opacity-soft)',
        disabled: 'var(--opacity-disabled)',
        muted: 'var(--opacity-muted)',
        scrim: 'var(--opacity-scrim)',
        chrome: 'var(--opacity-chrome)',
        visible: 'var(--opacity-visible)',
      },
    },
  },
  plugins: [],
};

export default config;
